
name: Android APK (debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0'

      # Crea la estructura Flutter mínima (solo Android)
      - name: Create Flutter skeleton (Android only)
        run: flutter create . --project-name shiny_hunt_sv --platforms=android --org com.tunombre

      - name: Install dependencies
        run: flutter pub add shared_preferences

      - name: Build APK (debug)
        run: flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
